const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/pouring-honey-on-pancakes.jpeg',
    desc: `Buttermilk pancakes are a classic breakfast favorite known for their light and fluffy texture, and slightly tangy flavor.`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/diner-double.jpeg',
    desc: `Double Diner is a charming eatery that blends the classic diner experience with a modern twist.  `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/gogzilla-milkshake.webp',
    desc: `The Godzilla Milkshake is a monstrous treat that's both towering and delicious, perfect for those with a colossal sweet tooth. `,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/fourth.webp',
    desc: `Country Delight Breakfast is a hearty and satisfying meal that brings the warmth and comfort of country cooking to your table.  `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/egg.jpg',
    desc: `Egg Attack Lunch is a dynamic and protein-packed meal designed to satisfy your midday hunger with a delicious array of egg-centric dishes.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/oreo.webp',
    desc: `The Oreo Dream Shake is a decadent and dreamy dessert beverage that's perfect for cookie lovers.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/beacon.jpg',
    desc: `The Bacon Overflow Breakfast is a hearty and indulgent morning feast that celebrates the rich, smoky flavor of bacon in all its glory. `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/american-classic.jpg',
    desc: `hamburger soup, finger-licking buttermilk fried chicken waffle sandwiches and crispy potato skins with roasted tomato ketchup. `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/choclate-shake.jpg',
    desc: `The Quarantine Buddy Shake is a whimsical and comforting drink that became popular during times of isolation.`,
  },
];
export default menu;